# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d2b2ac0df0912c0344fbc4cb8894cafe0a3b68d180c9ae9ec444d370c408f6d2bc3bfdb621bcaf0f5ecdb815fbe06d0a2f64148a39ad3b75233e0b72fc419c

test:
  secret_key_base: f5a5ac26179c0a74f744b61f5b8c77ef459e82628ddd02d426eb9b41950209287b54f391a6f30030184ff027a5ba44b6404cd232231abc1b03300317cf8751f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
